name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  BuildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release --split-per-abi
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Android
          path: build/app/outputs/flutter-apk

  BuildWindows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build EXE
        run: flutter build windows --release
      - name: Upload ZIP
        uses: actions/upload-artifact@v3
        with:
          name: Windows-x86_64
          path: build\windows\runner\Release

  Release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - BuildAndroid
      - BuildWindows
    steps:
      - name: Make dir
        run: mkdir artf release
      - name: Get Windows Release
        uses: actions/download-artifact@v3
        with:
          name: Windows-x86_64
          path: artf/windows
      - name: Get Android Release
        uses: actions/download-artifact@v3
        with:
          name: Android
          path: release
      - name: Compress Windows Release
        run: |
          cd artf/windows
          zip -r ../../release/windows.zip *
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ github.token }}
          GHR_REPLACE: true
          GHR_TITLE: ${{ needs.build-dist-bundle.outputs.version }}
          GHR_DRAFT: true
